//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCADA {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageString() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCADA.MessageString", typeof(MessageString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 线程异常 的本地化字符串。
        /// </summary>
        internal static string Application_ThreadException {
            get {
                return ResourceManager.GetString("Application_ThreadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未处理的异常 的本地化字符串。
        /// </summary>
        internal static string Application_UnhandleException {
            get {
                return ResourceManager.GetString("Application_UnhandleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消当前断刀报警。请确认是否为真实断刀？ 的本地化字符串。
        /// </summary>
        internal static string CNCForm_ToolBrokenInfo {
            get {
                return ResourceManager.GetString("CNCForm_ToolBrokenInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警内容 的本地化字符串。
        /// </summary>
        internal static string EquipmentCheck_CheckdataGridView_title_Content {
            get {
                return ResourceManager.GetString("EquipmentCheck_CheckdataGridView_title_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备编码 的本地化字符串。
        /// </summary>
        internal static string EquipmentCheck_CheckdataGridView_title_DeviceCode {
            get {
                return ResourceManager.GetString("EquipmentCheck_CheckdataGridView_title_DeviceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string EquipmentCheck_CheckdataGridView_title_Name {
            get {
                return ResourceManager.GetString("EquipmentCheck_CheckdataGridView_title_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        internal static string EquipmentCheck_CheckdataGridView_title_SN {
            get {
                return ResourceManager.GetString("EquipmentCheck_CheckdataGridView_title_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        internal static string EquipmentCheck_CheckdataGridView_title_Status {
            get {
                return ResourceManager.GetString("EquipmentCheck_CheckdataGridView_title_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机床 的本地化字符串。
        /// </summary>
        internal static string EquipmentCheck_Machine {
            get {
                return ResourceManager.GetString("EquipmentCheck_Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进给保持 的本地化字符串。
        /// </summary>
        internal static string EquipmentCheck_Status_Cycling {
            get {
                return ResourceManager.GetString("EquipmentCheck_Status_Cycling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 急停 的本地化字符串。
        /// </summary>
        internal static string EquipmentCheck_Status_EStop {
            get {
                return ResourceManager.GetString("EquipmentCheck_Status_EStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空闲 的本地化字符串。
        /// </summary>
        internal static string EquipmentCheck_Status_Idle {
            get {
                return ResourceManager.GetString("EquipmentCheck_Status_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        internal static string EquipmentCheck_Status_Normal {
            get {
                return ResourceManager.GetString("EquipmentCheck_Status_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线 的本地化字符串。
        /// </summary>
        internal static string EquipmentCheck_Status_Offline {
            get {
                return ResourceManager.GetString("EquipmentCheck_Status_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行 的本地化字符串。
        /// </summary>
        internal static string EquipmentCheck_Status_running {
            get {
                return ResourceManager.GetString("EquipmentCheck_Status_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入0-20的数字 的本地化字符串。
        /// </summary>
        internal static string SetForms_0_20 {
            get {
                return ResourceManager.GetString("SetForms_0_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入0-40的数字 的本地化字符串。
        /// </summary>
        internal static string SetForms_0_40 {
            get {
                return ResourceManager.GetString("SetForms_0_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string SetForms_Cancel {
            get {
                return ResourceManager.GetString("SetForms_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        internal static string SetForms_ChangePwd {
            get {
                return ResourceManager.GetString("SetForms_ChangePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ：第一次输入的密码和第二次输入的密码必须相同！ 的本地化字符串。
        /// </summary>
        internal static string SetForms_ChangePwd_SamePwd {
            get {
                return ResourceManager.GetString("SetForms_ChangePwd_SamePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ：修改密码成功！ 的本地化字符串。
        /// </summary>
        internal static string SetForms_ChangePwd_Succeed {
            get {
                return ResourceManager.GetString("SetForms_ChangePwd_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ：密码必须大于等于8！ 的本地化字符串。
        /// </summary>
        internal static string SetForms_ChangePwd_verify {
            get {
                return ResourceManager.GetString("SetForms_ChangePwd_verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string SetForms_Confirm {
            get {
                return ResourceManager.GetString("SetForms_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string SetForms_ContextMenu_Add {
            get {
                return ResourceManager.GetString("SetForms_ContextMenu_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string SetForms_ContextMenu_Delete {
            get {
                return ResourceManager.GetString("SetForms_ContextMenu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置数据已经更新，是否确认保存？ 的本地化字符串。
        /// </summary>
        internal static string SetForms_DataUpdate {
            get {
                return ResourceManager.GetString("SetForms_DataUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string SetForms_Information {
            get {
                return ResourceManager.GetString("SetForms_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string SetForms_Login {
            get {
                return ResourceManager.GetString("SetForms_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ：登陆失败！ 的本地化字符串。
        /// </summary>
        internal static string SetForms_Login_failed {
            get {
                return ResourceManager.GetString("SetForms_Login_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ：登陆成功！ 的本地化字符串。
        /// </summary>
        internal static string SetForms_Login_Succeed {
            get {
                return ResourceManager.GetString("SetForms_Login_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销 的本地化字符串。
        /// </summary>
        internal static string SetForms_Logout {
            get {
                return ResourceManager.GetString("SetForms_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ：注销成功！ 的本地化字符串。
        /// </summary>
        internal static string SetForms_Logout_Succeed {
            get {
                return ResourceManager.GetString("SetForms_Logout_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string SetForms_No {
            get {
                return ResourceManager.GetString("SetForms_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置参数保存 的本地化字符串。
        /// </summary>
        internal static string SetForms_parameter_Save {
            get {
                return ResourceManager.GetString("SetForms_parameter_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置参数保存成功 的本地化字符串。
        /// </summary>
        internal static string SetForms_parameter_Save_OK {
            get {
                return ResourceManager.GetString("SetForms_parameter_Save_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置数据已经改变，是否保存？ 的本地化字符串。
        /// </summary>
        internal static string SetForms_PosMessageStr1 {
            get {
                return ResourceManager.GetString("SetForms_PosMessageStr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置数据已经改变，需要先保存才能编辑输出输入信号，是否保存？ 的本地化字符串。
        /// </summary>
        internal static string SetForms_PosMessageStr2 {
            get {
                return ResourceManager.GetString("SetForms_PosMessageStr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你的操作权限不够！ 的本地化字符串。
        /// </summary>
        internal static string SetForms_RightNotEnough {
            get {
                return ResourceManager.GetString("SetForms_RightNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 的机器人的输入信号数量： 的本地化字符串。
        /// </summary>
        internal static string SetForms_Robot_InputSignalCount {
            get {
                return ResourceManager.GetString("SetForms_Robot_InputSignalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 的机器人的输出信号数量： 的本地化字符串。
        /// </summary>
        internal static string SetForms_Robot_OutputSignalCount {
            get {
                return ResourceManager.GetString("SetForms_Robot_OutputSignalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号为 的本地化字符串。
        /// </summary>
        internal static string SetForms_SN_As {
            get {
                return ResourceManager.GetString("SetForms_SN_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加用户成功：用户名 = 的本地化字符串。
        /// </summary>
        internal static string SetForms_User_Add {
            get {
                return ResourceManager.GetString("SetForms_User_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加用户失败：用户数量已经达到上限！ 的本地化字符串。
        /// </summary>
        internal static string SetForms_User_Add_VerifyCount {
            get {
                return ResourceManager.GetString("SetForms_User_Add_VerifyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加用户失败：用户名已经存在！ 的本地化字符串。
        /// </summary>
        internal static string SetForms_User_Add_VerifyExistUser {
            get {
                return ResourceManager.GetString("SetForms_User_Add_VerifyExistUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加用户失败：用户名长度不能小于1位！ 的本地化字符串。
        /// </summary>
        internal static string SetForms_User_Add_VerifyLen {
            get {
                return ResourceManager.GetString("SetForms_User_Add_VerifyLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加用户失败：密码长度不能小于6位！ 的本地化字符串。
        /// </summary>
        internal static string SetForms_User_Add_VerifyPwd {
            get {
                return ResourceManager.GetString("SetForms_User_Add_VerifyPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加用户失败：密码必须相同！ 的本地化字符串。
        /// </summary>
        internal static string SetForms_User_Add_VerifyPwdSame {
            get {
                return ResourceManager.GetString("SetForms_User_Add_VerifyPwdSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除用户成功：用户名 = 的本地化字符串。
        /// </summary>
        internal static string SetForms_User_Del {
            get {
                return ResourceManager.GetString("SetForms_User_Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理操作 的本地化字符串。
        /// </summary>
        internal static string SetForms_User_Manage {
            get {
                return ResourceManager.GetString("SetForms_User_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string SetForms_Yes {
            get {
                return ResourceManager.GetString("SetForms_Yes", resourceCulture);
            }
        }
    }
}
